language: node_js
node_js:
  - '5.12.0'
before_install:
  - npm install -g grunt-cli bower yo
  - gem install sass --version "=3.4.22"
  - gem install compass --version "=1.0.3"
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "a410450ed0bf"
  - COMMIT_AUTHOR_EMAIL: "imoffitt@barkleyrei.com"
